import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../../services/api';

interface Company { id: number; name: string; }
interface Role { id: number; title: string; company_id: number; }
interface Drive { id: number; title: string; company_name: string; job_title: string; drive_date: string; status: string; minimum_cgpa: number; }

export default function Drives() {
  const [companies, setCompanies] = useState<Company[]>([]); const [roles, setRoles] = useState<Role[]>([]); const [drives, setDrives] = useState<Drive[]>([]); const [selected, setSelected] = useState<number | null>(null); const [shortlist, setShortlist] = useState<any>(null); const [error, setError] = useState('');
  const [form, setForm] = useState({ company_id: '', job_role_id: '', title: '', description: '', job_description: '', package_lpa: '', location: '', eligibility_criteria: '', minimum_cgpa: '8', years: '2027', no_backlogs_required: true, registration_deadline: '', drive_date: '', drive_time: '', attendance_code: '' });
  const load = async () => { try { const [c, r, d] = await Promise.all([api.get('/admin/companies'), api.get('/admin/jobs'), api.get('/placements/drive-management')]); setCompanies(c.data); setRoles(r.data); setDrives(d.data); } catch (err: any) { setError(err.response?.data?.error?.message ?? 'Unable to load drives.'); } };
  useEffect(() => { void load(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await api.post('/placements/drive-management', { ...form, company_id: Number(form.company_id), job_role_id: Number(form.job_role_id), package_lpa: form.package_lpa ? Number(form.package_lpa) : null, minimum_cgpa: Number(form.minimum_cgpa), allowed_graduation_years: form.years.split(',').map(Number).filter(Boolean) }); setForm({ ...form, title: '', description: '', job_description: '', package_lpa: '', location: '', eligibility_criteria: '', registration_deadline: '', drive_date: '', drive_time: '', attendance_code: '' }); await load(); } catch (err: any) { setError(err.response?.data?.error?.message ?? 'Unable to create drive.'); } };
  const showShortlist = async (id: number) => { setSelected(id); const response = await api.get(`/placements/drive-management/${id}/shortlist`); setShortlist(response.data); };
  const toggle = async (driveId: number, profileId: number, active: boolean) => { if (active) await api.delete(`/placements/drive-management/${driveId}/shortlist`, { data: { profile_id: profileId } }); else await api.post(`/placements/drive-management/${driveId}/shortlist`, { profile_id: profileId }); await showShortlist(driveId); };
  const remove = async (id: number) => { await api.delete(`/placements/drive-management/${id}`); await load(); if (selected === id) setSelected(null); };
  return <div className="page-container-wide"><div className="page-header"><h1 className="page-title">Placement Drives</h1><Link to="/admin/dashboard" className="back-link">Back to Dashboard</Link></div>{error && <div className="alert alert-error">{error}</div>}
    <div className="form-card"><h2 className="form-title">Create Placement Drive</h2><form onSubmit={submit}><div className="form-grid">
      <label className="label-col">Company<select className="input" value={form.company_id} onChange={e => setForm({ ...form, company_id: e.target.value, job_role_id: '' })} required><option value="">Select company</option>{companies.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
      <label className="label-col">Job Role<select className="input" value={form.job_role_id} onChange={e => setForm({ ...form, job_role_id: e.target.value })} required><option value="">Select role</option>{roles.filter(r => !form.company_id || r.company_id === Number(form.company_id)).map(r => <option key={r.id} value={r.id}>{r.title}</option>)}</select></label>
      <label className="label-col">Drive title<input className="input" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="Aven Hospitality - Registered Students List" required /></label>
      <label className="label-col">Drive date<input type="date" className="input" value={form.drive_date} onChange={e => setForm({ ...form, drive_date: e.target.value })} required /></label><label className="label-col">Registration deadline<input type="datetime-local" className="input" value={form.registration_deadline} onChange={e => setForm({ ...form, registration_deadline: e.target.value })} /></label>
      <label className="label-col">Time<input className="input" value={form.drive_time} onChange={e => setForm({ ...form, drive_time: e.target.value })} /></label><label className="label-col">Location<input className="input" value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} /></label>
      <label className="label-col">Minimum CGPA<input type="number" step="0.1" className="input" value={form.minimum_cgpa} onChange={e => setForm({ ...form, minimum_cgpa: e.target.value })} /></label><label className="label-col">Passed-out years<input className="input" value={form.years} onChange={e => setForm({ ...form, years: e.target.value })} placeholder="2027, 2028" /></label>
      <label className="label-col">Package (LPA)<input type="number" step="0.1" className="input" value={form.package_lpa} onChange={e => setForm({ ...form, package_lpa: e.target.value })} /></label><label className="label-col">Attendance code<input className="input" value={form.attendance_code} onChange={e => setForm({ ...form, attendance_code: e.target.value })} required /></label>
    </div><label className="label-col mt-1">Eligibility criteria<textarea className="input" value={form.eligibility_criteria} onChange={e => setForm({ ...form, eligibility_criteria: e.target.value })} placeholder="Minimum 8.0 CGPA with no backlogs" /></label><label className="label-col mt-1">Description / notice<textarea className="input" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><label className="label-col mt-1">Job description<textarea className="input" value={form.job_description} onChange={e => setForm({ ...form, job_description: e.target.value })} /></label><label><input type="checkbox" checked={form.no_backlogs_required} onChange={e => setForm({ ...form, no_backlogs_required: e.target.checked })} /> No backlogs required</label><br /><button className="btn btn-primary">Publish Drive</button></form></div>
    <div className="job-list">{drives.map(d => <article className="job-card" key={d.id}><div className="job-card-header"><div><h2 className="job-title">{d.title}</h2><p className="job-company">{d.company_name} · {d.job_title} · {d.drive_date}</p></div><span>CGPA {d.minimum_cgpa}+</span></div><button className="btn btn-primary btn-sm" onClick={() => void showShortlist(d.id)}>View / Edit Shortlist</button> <button className="btn btn-danger btn-sm" onClick={() => void remove(d.id)}>Delete</button>{selected === d.id && shortlist && <div className="table-wrapper"><table className="table"><thead><tr><th>Student</th><th>CGPA</th><th>Year</th><th>Eligibility</th><th>Shortlisted</th></tr></thead><tbody>{shortlist.eligible_candidates.map((student: any) => <tr key={student.profile_id}><td>{student.student_name}</td><td>{student.cgpa ?? 'Not provided'}</td><td>{student.graduation_year ?? 'Not provided'}</td><td>{student.eligible ? 'Eligible' : student.eligibility_reasons.join(' ')}</td><td><button className="btn btn-sm" disabled={!student.eligible && !student.shortlisted} onClick={() => void toggle(d.id, student.profile_id, student.shortlisted)}>{student.shortlisted ? 'Remove' : student.eligible ? 'Add' : 'Ineligible'}</button></td></tr>)}</tbody></table></div>}</article>)}</div>
  </div>;
}
